apiVersion: v1
kind: Service
metadata:
  name: alfred-github-svc
spec:
  type: LoadBalancer
  selector:
    app: alfred-github-app
  ports:
    - protocol: "TCP"
      port: 3200
      targetPort: 80
      nodePort: 30020

